services:

  front:
    image: nginx:alpine
    container_name: front
    volumes:
      - ./front/dist:/usr/share/nginx/html
      - ./front/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-net
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "3000:3000"
    env_file:
      - back/.env.docker
    environment:
      - PUBLIC_URL=http://158.255.5.107/static
    volumes:
      - ./back/dist/public:/app/dist/public
    networks:
      - app-net
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: "3262867#Kamamotoadmin"
    entrypoint: ["mongod", "--auth", "--bind_ip", "0.0.0.0"]
    env_file:
      - back/.env.docker
    volumes:
      # - ./mongo/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./mongo/dump_test:/data/db
    restart: always
    networks:
      - app-net

networks:
  app-net:
    name: app-net
    driver: bridge
