services:

  front:
    image: nginx:alpine
    container_name: front
    volumes:
      - ./front/dist:/usr/share/nginx/html
      - ./front/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-net
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "3000:3000"
    env_file:
      - back/.env.docker
    volumes:
      - ./back/src/public:/app/dist/public
    networks:
      - app-net
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
    env_file:
      - back/.env.docker
    volumes:
      - ./mongo/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./mongo/db_dump_full:/db_dump_full
      - ./mongo/mongod.conf:/usr/local/etc/mongod.conf
    networks:
      - app-net

networks:
  app-net:
    name: app-net
    driver: bridge
