import 'dotenv/config';

const {
	NODE_ENV = 'CHECK_NODE_ENV',
	JWT_SECRET = 'CHECK_JWT_SECRET',
	BASE_URL = 'CHECK_BASE_URL',
	PORT = 'CHECK_PORT',
	DB_HOST = 'CHECK_DB_HOST',
	DB_PORT = 'CHECK_DB_PORT',
	DB_NAME = 'CHECK_DB_NAME',
	DB_USER = 'CHECK_DB_USER',
	DB_PASS = 'CHECK_DB_PASS',
	STATIC_URL = `${BASE_URL}:${PORT}/static`,
} = process.env;

export { BASE_URL, DB_HOST, DB_NAME, DB_PASS, DB_PORT, DB_USER, JWT_SECRET, NODE_ENV, PORT, STATIC_URL };
