import path from 'node:path';
import 'dotenv/config';

const {
	PORT = 0,
	NODE_ENV = 'CHECK_YOUR_DOTENV',
	JWT_SECRET = 'CHECK_YOUR_DOTENV',
	BASE_URL = 'CHECK_YOUR_DOTENV',
	DB_HOST = 'CHECK_YOUR_DOTENV',
	DB_PORT = 'CHECK_YOUR_DOTENV',
	DB_NAME = 'CHECK_YOUR_DOTENV',
	DB_USER = 'CHECK_YOUR_DOTENV',
	DB_PASS = 'CHECK_YOUR_DOTENV',
} = process.env;

const PUBLIC_FOLDER = path.join(__dirname, 'public');

export { BASE_URL, DB_HOST, DB_NAME, DB_PASS, DB_PORT, DB_USER, JWT_SECRET, NODE_ENV, PORT, PUBLIC_FOLDER };
