export enum CeramicStyleType {
  agano = 'Агано',
  akahada = 'Акахада',
  arita = 'Арита',
  bizen = 'Бидзэн',
  celadon = 'Селадон',
  echizen = 'Этидзэн',
  glass = 'Стекло',
  hakuji = 'Хакудзи',
  hagi = 'Хаги',
  mino = 'Мино',
  kiyomizu = 'Киёмидзу',
  kohiki = 'Кохики',
  kyo = 'Кё',
  oribe = 'Орибэ',
  other = 'другой',
  raku = 'Раку',
  seiji = 'Сэидзи',
  seto = 'Сэто',
  shigaraki = 'Сигараки',
  shino = 'Сино',
  takatori = 'Такатори',
  tokoname = 'Токонамэ',
  unknown = 'не определён'
}
