export enum ExhibitComplectation {
  bowl = 'чаша',
  chaire = 'керамическая чайница',
  chashaku = 'бамбуковаля лопаточка',
  cup = 'пиала',
  cups2 = 'две пиалы',
  cups3 = 'три пиалы',
  kama = 'чугунный котёл с крышкой',
  kamakan = 'кольца для переноса котла',
  kogo = 'контейнер из двух частей',
  natsume = 'чайница лакированная',
  plate = 'тарелка',
  protectiveCloth = 'защитная ткань',
  protectiveCloths2 = 'две защитных ткани',
  paperDocument = 'бумажный документ',
  paperDocuments2 = 'два бумажных документа',
  shifuku = 'мешочек сифуку',
  teapot = 'чайник с крышкой',
  tomobakoBamboo = 'бамбуковая коробка',
  tomobakoCarton = 'картонная коробка',
  tomobakoWooden = 'деревянная коробка',
  vase = 'ваза'
}
