import type { Incense } from '@/variables/incences.types';
import { Features } from '@/variables/features';
import { Ingredients } from '@/variables/incences.types';
import { manufacturers } from '@/variables/manufacturers';
import { origin } from '@/variables/origin';

export const bayeidoIncences: Incense[] = [
	{
		slug: 'kobunboku',
		title: 'Кобунбоку',
		originalTitle: '好文木',
		description: 'Кобунбоку — очень популярный аромат для медитации, воплощающий в себе «цветок мира» — цветущую сливу. Этот изысканный аромат представляет собой сочетание сандалового дерева, борнеола, гвоздики, корицы и других традиционных специй. Выпущенный 100 лет назад, он является бестселлером в Японии и одним из флагманских ароматов компании Байэидо. Аромат сладковатый, сухой, элегантный и очень приятный. Как и все благовония Бэйэидо - это традиционное пряно-древесное сочетание.',
		photos: ['2111985.webp', '2111992.webp', '2111980.webp', '2111981.webp', '2111982.webp', '2111986.webp', '2111989.webp', '2111987.webp', '2111991.webp'],
		origin: origin.japan,
		manufacturer: manufacturers.baieido,
		series: manufacturers.baieido.series?.kobunboku,
		ingredients: [Ingredients.sandalwood, Ingredients.borneol, Ingredients.clove, Ingredients.cinnamon, Ingredients.herbsMedicine],
		features: [Features.daily, Features.natural],
		burnTime: 30,
		lenght: 13,
		price: 0,
		pricePerStick: 28,
		isActive: true,
		inStock: true,
	},

	{
		slug: 'kaden-kobunboku',
		title: 'Кадэн Кобунбоку',
		originalTitle: '家伝好文木',
		description: 'Кадэн переводится как "старый семейный секрет", это тщательно созданный путем смешивания двадцати видов натуральных ароматов рецепт, включающий все более редкие натуральные агар Цукигасэ и сандаловое дерево. Кадэн Кобунбоку очень популярен благодаря своему теплому, мягкому, горьковато-сладкому аромату, идеально подходящему для медитации.',
		photos: ['2111997.webp', '2111994.webp', '2111995.webp', '2111998.webp', '2111999.webp', '2112000.webp', '2112001.webp', '2112002.webp', '2112004.webp'],
		origin: origin.japan,
		manufacturer: manufacturers.baieido,
		series: manufacturers.baieido.series?.kobunboku,
		ingredients: [Ingredients.aloeswoodVietnamese, Ingredients.sandalwood, Ingredients.borneol, Ingredients.clove, Ingredients.cinnamon, Ingredients.herbsMedicine],
		features: [Features.daily, Features.natural],
		burnTime: 30,
		lenght: 13,
		price: 0,
		pricePerStick: 28,
		isActive: true,
		inStock: true,
	},

	{
		slug: 'bikou-kobunboku',
		title: 'Бико Кобунбоку',
		originalTitle: '微香好文木',
		description: 'Название Бико Кобунбоку означает "нежный аромат", и это более тонкая версия высоко ценимой формулы сливового аромата классического Кобунбоку. Бико - более мягкий и нежный, с едва уловимыми нотками корицы и китайских медицинских трав, прекрасно сочетающихся с оттенком агара на сандаловой основе. Бико Кобунбоку производит очень мало дыма и широко используется в дзен-до по всему миру.',
		photos: ['2111977.webp', '2111968.webp', '2111969.webp', '2111970.webp', '2111971.webp', '2111972.webp', '2111975.webp', '2111976.webp', '2111978.webp'],
		origin: origin.japan,
		manufacturer: manufacturers.baieido,
		series: manufacturers.baieido.series?.kobunboku,
		ingredients: [Ingredients.sandalwood, Ingredients.borneol, Ingredients.clove, Ingredients.cinnamon, Ingredients.herbsMedicine],
		features: [Features.lowSmoke, Features.daily, Features.natural],
		burnTime: 30,
		lenght: 13,
		price: 0,
		pricePerStick: 32,
		isActive: true,
		inStock: true,
	},

	{
		slug: '',
		title: '',
		originalTitle: '',
		description: '',
		photos: [],
		origin: origin.unknown,
		manufacturer: manufacturers.unknown,
		series: undefined,
		ingredients: [],
		features: [Features.none],
		burnTime: 0,
		lenght: 0,
		price: 0,
		pricePerStick: 0,
		isActive: false,
		inStock: false,
	},
];
