import type { Incense } from '@/variables/incences.types';
import { Features } from '@/variables/features';
import { Ingredients } from '@/variables/ingredients';
import { manufacturers } from '@/variables/manufacturers/_index';
import { origin } from '@/variables/origin';
import { stock } from '@/variables/stock';

const premium: Incense[] = [
	{
		title: 'Рэндзан (Горный хребет)',
		originalTitle: '連山',
		slug: 'renzan',
		description: 'Рэндзан — это сладковатый, глубокий, насыщенный, но в то же время знакомый аромат, сочетающий в себе ноты агара, сандала и традиционных китайских медицинских трав. Сложный, сухой древесный, очень приятный для слушания и прекрасный для знакомства с традиционными японскими ароматами.',
		photos: ['P1013740.webp', 'P1013746.webp', 'P1013738.webp', 'P1013739.webp', 'P1013742.webp', 'P1013745.webp', 'P1013747.webp'],
		manufacturer: manufacturers.tennendo,
		series: manufacturers.tennendo.series?.premium,
		ingredients: [Ingredients.aloeswood, Ingredients.sandalwood, Ingredients.clove, Ingredients.cinnamon, Ingredients.spices],
		features: [Features.premium, Features.natural],
		burnTime: 30,
		lenght: 14,
		origin: origin.japan,
		price: 0,
		pricePerStick: 28,
		quantity: stock.tennendo?.renzan || 0,
		isActive: true,
		inStock: true,
	},

	{
		title: 'Карафунэ (Заморский корабль)',
		originalTitle: '唐舟',
		slug: 'karafune',
		description: 'Карафунэ обладает нежным, освежающим традиционным ароматом. В составе исключительно натуральные компоненты, создающие успокаивающий и мягкий вкус, с легким, продолжительным послевкусием. Идеально подходит для релаксации или медитации.',
		photos: ['P1013750.webp', 'P1013757.webp', 'P1013751.webp', 'P1013749.webp', 'P1013748.webp', 'P1013754.webp'],
		manufacturer: manufacturers.tennendo,
		series: manufacturers.tennendo.series?.premium,
		ingredients: [Ingredients.sandalwood, Ingredients.clove, Ingredients.cinnamon, Ingredients.kaikou, Ingredients.fennel, Ingredients.kaikou, Ingredients.herbsMedicine],
		features: [Features.premium, Features.natural],
		burnTime: 25,
		lenght: 14,
		origin: origin.japan,
		price: 0,
		pricePerStick: 24,
		quantity: stock.tennendo?.karafune || 0,
		isActive: true,
		inStock: true,
	},

	{
		title: 'Сингон (Мантра)',
		originalTitle: '真言',
		slug: 'shingon',
		description: 'Сингон — интересный вариант сандалового дерева с мускусными нотами, полученными из растительных компонентов. Прекрасный образец для знакомства с традиционным японским сандалом. Он обладает хорошим сбалансированным ароматом, находящимся где-то между «влажным» и «сухим» сандаловым запахом. Даже сегодня этот аромат часто можно услышать в храмах и он хорошо подходит в качестве благовония для буддийского алтаря или медитации.',
		photos: ['P1013729.webp', 'P1013725.webp', 'P1013726.webp', 'P1013728.webp', 'P1013730.webp'],
		manufacturer: manufacturers.tennendo,
		series: manufacturers.tennendo.series?.premium,
		ingredients: [Ingredients.sandalwood, Ingredients.spices],
		features: [Features.premium, Features.natural],
		burnTime: 25,
		lenght: 14,
		origin: origin.japan,
		price: 0,
		pricePerStick: 30,
		quantity: stock.tennendo?.shingon || 0,
		isActive: true,
		inStock: true,
	},

	{
		title: 'Корокан (Сандал)',
		originalTitle: '鴻臚館',
		slug: 'khorokan',
		description: 'Сандал Корокана производится из чистейшего старого горного сандала из Майсура (с добавлением лишь табуноки в качестве связующего вещества), Индия. Это невероятно насыщенный и мягкий аромат с тонкой сладостью и характерными пряными нотками располагает к отдыху и расслаблению. Настоятельно рекомендуется ценителям сандалового дерева. *табуноки (также называемая макко) — это кора дерева Machilus thunbergii, которая служит натуральным водорастворимым клеем и основой для благовоний.',
		photos: ['P1014517.webp', 'P1014519.webp', 'P1014520.webp', 'P1014521.webp', 'P1014522.webp', 'P1014524.webp', 'P1014525.webp'],
		manufacturer: manufacturers.tennendo,
		series: manufacturers.tennendo.series?.premium,
		ingredients: [Ingredients.sandalwood, Ingredients.japaneseBayTreeBark],
		features: [Features.premium, Features.natural],
		burnTime: 25,
		lenght: 14,
		origin: origin.japan,
		price: 0,
		pricePerStick: 28,
		quantity: stock.tennendo?.khorokan || 0,
		isActive: true,
		inStock: true,
	},

	{
		title: 'Нюко (Ладан)',
		originalTitle: '乳香',
		slug: 'nyuko',
		description: 'Полученный с эксклюзивного разрешения султаната Омана, ладан из Дофара в благовониях от Тэннэндо заслужил репутацию высококачественного благовония. Освежающе сладкий аромат с фруктово-цитрусовыми верхними нотами. ',
		photos: ['P1014527.webp', 'P1014528.webp', 'P1014532.webp', 'P1014529.webp', 'P1014531.webp', 'P1014530.webp'],
		manufacturer: manufacturers.tennendo,
		series: manufacturers.tennendo.series?.premium,
		ingredients: [Ingredients.frankincense],
		features: [Features.premium, Features.natural],
		burnTime: 25,
		lenght: 14,
		origin: origin.japan,
		price: 0,
		pricePerStick: 34,
		quantity: stock.tennendo?.nyuko || 0,
		isActive: true,
		inStock: true,
	},
];

export const tennendoIncences: Incense[] = [...premium];
