import type { Incense } from '@/variables/incences.types';
import { Features } from '@/variables/features';
import { Ingredients } from '@/variables/ingredients';
import { manufacturers } from '@/variables/manufacturers/_index';
import { origin } from '@/variables/origin';
import { stock } from '@/variables/stock';

const karaku: Incense[] = [
	{
		title: 'Бъякудан (Сандал)',
		originalTitle: '白檀',
		slug: 'byakudan',
		description: 'Бъякудан — это превосходные благовония из чистого сандалового дерева, изготовленные из высококачественного сандала сорта Розан. Аромат густой, древесный и мягкий. Идеально подходит для ежедневного использования.',
		photos: ['P1014038.webp', 'P1014040.webp', 'P1014039.webp', 'P1014043.webp', 'P1014041.webp', 'P1014044.webp', 'P1014042.webp'],
		manufacturer: manufacturers.yamadamatsu,
		series: manufacturers.yamadamatsu.series?.karaku,
		ingredients: [Ingredients.sandalwoodRozan],
		features: [Features.daily],
		burnTime: 25,
		lenght: 13.5,
		origin: origin.japan,
		price: 0,
		pricePerStick: 22,
		quantity: stock.yamadamatsu?.byakudan || 0,
		isActive: true,
		inStock: true,
	},

	{
		title: 'Дзинко',
		originalTitle: '',
		slug: 'jinko',
		description: 'Дзинко — это успокаивающий аромат агара, предназначенный для ежедневного использования. Идеально подходит для небольших помещений и медитации. Насыщенный, глубокий и спокойный аромат. Идеально подходит для случаев, когда нежелательно использование сильных ароматов и для небольших помещений.',
		photos: ['PC013444.webp', 'PC013442.webp', 'PC013443.webp', 'PC013445.webp', 'PC013446.webp', 'PC013447.webp'],
		manufacturer: manufacturers.yamadamatsu,
		series: manufacturers.yamadamatsu.series?.karaku,
		ingredients: [Ingredients.aloeswood],
		features: [Features.daily],
		burnTime: 25,
		lenght: 13.5,
		origin: origin.japan,
		price: 0,
		pricePerStick: 22,
		quantity: stock.yamadamatsu?.jinko || 0,
		isActive: true,
		inStock: true,
	},

	{
		title: 'Сёрэн',
		originalTitle: '',
		slug: 'shoren',
		description: 'Сёрэн — это свежий цветочный сандал, напоминающий аромат голубых лотосов, с мягким, долго сохраняющимся сладким послевкусием. Идеально подходит для ежедневного использования, медитации и случаев, когда нежелательно сильное ароматическое воздействие.',
		photos: ['P1014044.webp', 'P1014046.webp', 'P1014047.webp', 'P1014048.webp', 'P1014049.webp', 'P1014050.webp'],
		manufacturer: manufacturers.yamadamatsu,
		series: manufacturers.yamadamatsu.series?.karaku,
		ingredients: [Ingredients.sandalwoodSweet, Ingredients.florals],
		features: [Features.daily],
		burnTime: 25,
		lenght: 13.5,
		origin: origin.japan,
		price: 0,
		pricePerStick: 22,
		quantity: stock.yamadamatsu?.shoren || 0,
		isActive: true,
		inStock: true,
	},

	{
		title: 'Сэйфу',
		originalTitle: '清風',
		slug: 'seifu',
		description: 'Сэйфу (Свежий бриз) — мягкий, сочный аромат сандалового дерева, идеально подходящий для ежедневного использования. Сладкий, цветочный и древесный. Сладковатый аромат палочки раскрывается плотной медовой сладостью при воскуривании.',
		photos: ['P1014031.webp', 'P1014033.webp', 'P1014029.webp', 'P1014034.webp', 'P1014035.webp', 'P1014036.webp', 'P1014037.webp'],
		manufacturer: manufacturers.yamadamatsu,
		series: manufacturers.yamadamatsu.series?.karaku,
		ingredients: [Ingredients.sandalwoodSweet],
		features: [Features.daily, Features.natural],
		burnTime: 25,
		lenght: 13.5,
		origin: origin.japan,
		price: 0,
		pricePerStick: 20,
		quantity: stock.yamadamatsu?.seifu || 0,
		isActive: true,
		inStock: true,
	},
];

const premium: Incense[] = [
	{
		title: 'Кагэцу',
		originalTitle: '',
		slug: 'kagetsu',
		description: 'В аромате Кагэцу используется высококачественный майсурский сандал из Индии, обладающий мягким, нежно-сладким ароматом.',
		photos: ['P1014066.webp', 'P1014060.webp', 'P1014061.webp', 'P1014064.webp', 'P1014062.webp', 'P1014065.webp', 'P1014063.webp'],
		manufacturer: manufacturers.yamadamatsu,
		series: manufacturers.yamadamatsu.series?.premium,
		ingredients: [Ingredients.sandalwoodIndian],
		features: [Features.premium, Features.natural],
		burnTime: 30,
		lenght: 13.5,
		origin: origin.japan,
		price: 0,
		pricePerStick: 28,
		quantity: stock.yamadamatsu?.kagetsu || 0,
		isActive: true,
		inStock: true,
	},

	{
		title: 'Каё',
		originalTitle: '',
		slug: 'kayo',
		description: 'В аромате Каё, созданном из отборного сандалового дерева высшего сорта из Майсура, ощущаются глубокие, насыщенные и элегантные ноты старого горного сандала. Гармонично сочетая сухие и полусладкие тона, Каё передает аромат роскошной выдержанной древесины, отличающийся глубиной и богатством.',
		photos: ['P1014067.webp', 'P1014070.webp', 'P1014068.webp', 'P1014071.webp', 'P1014074.webp', 'P1014073.webp'],
		manufacturer: manufacturers.yamadamatsu,
		series: manufacturers.yamadamatsu.series?.premium,
		ingredients: [Ingredients.sandalwoodIndian],
		features: [Features.premium, Features.natural],
		burnTime: 30,
		lenght: 13.5,
		origin: origin.japan,
		price: 0,
		pricePerStick: 32,
		quantity: stock.yamadamatsu?.kayo || 0,
		isActive: true,
		inStock: true,
	},

	{
		title: 'Ообай',
		originalTitle: '',
		slug: 'oubai',
		description: 'Обладая уникальным нежным растительным ароматом, Ообай изготовлен из традиционных натуральных ароматических ингредиентов на сандаловой основе. Создаёт успокаивающий и расслабляющий, живой, полусладкий и прохладный аромат удивительной глубины.',
		photos: ['P1014076.webp', 'P1014079.webp', 'P1014080.webp', 'P1014075.webp', 'P1014078.webp', 'P1014081.webp'],
		manufacturer: manufacturers.yamadamatsu,
		series: manufacturers.yamadamatsu.series?.premium,
		ingredients: [Ingredients.sandalwood, Ingredients.campfor, Ingredients.nard],
		features: [Features.premium, Features.natural],
		burnTime: 30,
		lenght: 13.5,
		origin: origin.japan,
		price: 0,
		pricePerStick: 25,
		quantity: stock.yamadamatsu?.oubai || 0,
		isActive: true,
		inStock: true,
	},
];

export const yamadamatsuIncences: Incense[] = [...karaku, ...premium];
