import type { Marker } from '@/components/visitor/Map/map.types';

export const sixOldKilns: Marker[] = [
	{ geocode: [34.877685, 136.058957], tooltip: 'Сигараки', kanji: '信楽焼', romaji: 'shigaraki', popup: 'Определена как Традиционное народное ремесло в 1975', image: 'shigaraki.webp' },
	{ geocode: [34.738748, 134.160282], tooltip: 'Бидзэн', kanji: '備前焼', romaji: 'bizen', popup: 'Определена как Традиционное народное ремесло в 1982', image: 'bizen.webp' },
	{ geocode: [35.970000, 136.068056], tooltip: 'Этидзэн', kanji: '越前焼', romaji: 'echizen', popup: 'Определена как Традиционное народное ремесло в 1986', image: 'echizen.webp' },
	{ geocode: [34.883987, 136.856262], tooltip: 'Токонамэ', kanji: '常滑焼', romaji: 'tokoname', popup: 'Определена как Традиционное народное ремесло в 1976', image: 'tokoname.webp' },
	{ geocode: [34.692263, 135.195586], tooltip: 'Тамба (Танба)', kanji: '丹波立杭焼', romaji: 'tamba tanba tachikui', popup: 'Определена как Традиционное народное ремесло в 1978', image: 'tamba.webp' },
	{ geocode: [35.224660, 137.107372], tooltip: 'Сэто', kanji: '瀬戸焼', romaji: 'seto', popup: '', image: 'seto.webp' },
];

export const sevenKilnsOfEnshu: Marker[] = [
	{ geocode: [33.702067, 130.783679], tooltip: 'Агано', kanji: '上野焼', romaji: 'agano', popup: 'Определена как Традиционное <br> народное ремесло в 1983 году', image: 'agano.webp' },
	{ geocode: [34.669432, 135.798605], tooltip: 'Акахада', kanji: '赤膚焼', romaji: 'akahada', popup: '', image: 'akahada.webp' },
	{ geocode: [34.988499, 135.894090], tooltip: 'Дзэдзэ', kanji: '膳所焼', romaji: 'zeze', popup: '', image: 'zeze.webp' },
	{ geocode: [34.910988, 135.812608], tooltip: 'Асахи', kanji: '朝日焼', romaji: 'asahi', popup: '', image: 'asahi.webp' },
	{ geocode: [34.861668, 135.624129], tooltip: 'Кособэ', kanji: '古曾部', romaji: 'kosobe', popup: '', image: 'kosobe.webp' },
	{ geocode: [34.837026, 138.163954], tooltip: 'Ситоро', kanji: '志戸呂焼', romaji: 'shitoro', popup: '', image: 'shitoro.webp' },
	{ geocode: [33.579506, 130.351696], tooltip: 'Такатори', kanji: '高取焼', romaji: 'takatori', popup: '', image: 'takatori.webp' },
];

export const traditionalKilns: Marker[] = [
	{ geocode: [37.452575, 139.889752], tooltip: 'Айдзу Хонго', kanji: '会津本郷焼', romaji: 'aizu hongo', popup: 'Определена как Традиционное <br> народное ремесло в 1993 году', image: 'aizu-hongo.webp' },
	{ geocode: [35.225345, 137.128556], tooltip: 'Акадзу', kanji: '赤津焼', romaji: 'akazu', popup: 'Определена как Традиционное <br> народное ремесло в 1977 году', image: 'akazu.webp' },
	{ geocode: [32.386185, 130.177620], tooltip: 'Амакуса', kanji: '天草陶磁器', romaji: 'amakusa tojiki yaki', popup: 'Определена как Традиционное <br> народное ремесло в 2003 году', image: 'amakusa.webp' },
	{ geocode: [34.978522, 136.624900], tooltip: 'Ёккаити Банко', kanji: '萬古焼', romaji: 'yokkaichi banko', popup: 'Определена как Традиционное <br> народное ремесло в 1979 году', image: 'banko.webp' },
	{ geocode: [35.473484, 133.053297], tooltip: 'Ивами', kanji: '石見焼', romaji: 'iwami', popup: 'Определена как Традиционное <br> народное ремесло в 1994 году', image: 'iwami.webp' },
	{ geocode: [34.730283, 136.508588], tooltip: 'Ига', kanji: '伊賀焼', romaji: 'iga', popup: 'Определена как Традиционное <br> народное ремесло в 1982 году', image: 'iga.webp' },
	{ geocode: [35.544226, 134.820103], tooltip: 'Идзуси', kanji: '出石焼', romaji: 'izushi', popup: 'Определена как Традиционное <br> народное ремесло в 1980 году', image: 'izushi.webp' },
	{ geocode: [33.236371, 129.892132], tooltip: 'Имари / Арита', kanji: '伊万里焼 有田焼', romaji: 'imari arita', popup: 'Определены как Традиционные <br> народные ремёсла в 1977 году', image: 'arita.webp' },
	{ geocode: [33.441394, 129.967726], tooltip: 'Карацу', kanji: '唐津焼', romaji: 'karatsu', popup: 'Определена как Традиционное <br> народное ремесло в 1988 году', image: 'karatsu.webp' },
	{ geocode: [36.372701, 140.261230], tooltip: 'Касама', kanji: '笠間焼', romaji: 'kasama', popup: 'Определена как Традиционное <br> народное ремесло в 1992 году', image: 'kasama.webp' },
	{ geocode: [35.012839, 135.780895], tooltip: 'Кё / Киёмидзу', kanji: '京焼 清水焼', romaji: 'kyo kiyomizu', popup: 'Определены как Традиционные <br> народные ремёсла в 1977 году <br> <a target="_blank" href="/ceramic-styles/kyo">Читать статью</a>', image: 'kyo.webp' },
	{ geocode: [33.432530, 130.847227], tooltip: 'Коисивара', kanji: '小石原焼', romaji: 'koishiwara', popup: 'Определена как Традиционное <br> народное ремесло в 1975 году', image: 'koishiwara.webp' },
	{ geocode: [36.302762, 136.310187], tooltip: 'Кутани', kanji: '九谷焼', romaji: 'kutani', popup: 'Определена как Традиционное <br> народное ремесло в 1975 году', image: 'kutani.webp' },
	{ geocode: [36.465884, 140.105830], tooltip: 'Масико', kanji: '益子焼', romaji: 'mashiko', popup: 'Определена как Традиционное <br> народное ремесло в 1979 году', image: 'mashiko.webp' },
	{ geocode: [33.177025, 129.724736], tooltip: 'Микавати', kanji: '三川内焼', romaji: 'mikawachi', popup: 'Определена как Традиционное <br> народное ремесло в 1978 году <br> <a target="_blank" href="/ceramic-styles/mikawachi">Читать статью</a>', image: 'mikawachi.webp' },
	{ geocode: [35.381446, 137.153613], tooltip: 'Мино', kanji: '美濃焼', romaji: 'mino', popup: 'Определена как Традиционное <br> народное ремесло в 1978 году', image: 'mino.webp' },
	{ geocode: [37.494573, 141.000652], tooltip: 'Обори Cома', kanji: '大堀相馬焼', romaji: 'obori soma', popup: 'Определена как Традиционное <br> народное ремесло в 1978 году', image: 'obori-soma.webp' },
	{ geocode: [34.168590, 134.540929], tooltip: 'Отани', kanji: '大谷焼', romaji: 'otani', popup: 'Определена как Традиционное <br> народное ремесло в 2003 году', image: 'otani.webp' },
	{ geocode: [38.018274, 138.368385], tooltip: 'Садо Мумёи', kanji: '無名異焼', romaji: 'sado mumyoi', popup: 'Определена как Традиционное <br> народное ремесло в 2024 году', image: 'sado-mumyoi.webp' },
	{ geocode: [31.598611, 130.554720], tooltip: 'Сацума', kanji: '薩摩焼', romaji: 'satsuma', popup: 'Определена как Традиционное <br> народное ремесло в 2002 году', image: 'satsuma.webp' },
	{ geocode: [32.976934, 130.475048], tooltip: 'Сёдай', kanji: '小代焼', romaji: 'shodai', popup: 'Определена как Традиционное <br> народное ремесло в 2003 году', image: 'shodai.webp' },
	{ geocode: [35.180295, 136.906712], tooltip: 'Сансю Онигавара', kanji: '三州鬼瓦', romaji: 'sanshu onigawara', popup: 'Определена как Традиционное <br> народное ремесло в 2017 году', image: 'sanshu-onigawara.webp' },
	{ geocode: [35.215660, 137.095372], tooltip: 'Сэто Сомэцукэ', kanji: '瀬戸焼 染付', romaji: 'seto sometsuke', popup: 'Определена как Традиционное <br> народное ремесло в 1997 году', image: 'seto-sometsuke.webp' },
	{ geocode: [33.759081, 132.789792], tooltip: 'Тобэ', kanji: '砥部焼', romaji: 'tobe', popup: 'Определена как Традиционное <br> народное ремесло в 1976 году', image: 'tobe.webp' },
	{ geocode: [33.141832, 129.912049], tooltip: 'Хасами', kanji: '波佐見焼', romaji: 'hasami', popup: 'Определена как Традиционное <br> народное ремесло в 1978 году', image: 'hasami.webp' },
	{ geocode: [34.422368, 131.409853], tooltip: 'Хаги', kanji: '萩焼', romaji: 'hagi', popup: 'Определена как Традиционное <br> народное ремесло в 2002 году <br> <a target="_blank" href="/ceramic-styles/hagi">Читать статью</a>', image: 'hagi.webp' },
	{ geocode: [26.216389, 127.689349], tooltip: 'Цубоя', kanji: '壺屋焼', romaji: 'tsuboya', popup: 'Определена как Традиционное <br> народное ремесло в 1976 году', image: 'tsuboya.webp' },
];

export const otherKilns: Marker[] = [
	{ geocode: [38.48234, 140.34454], tooltip: 'Готэн', kanji: '碁点焼', romaji: 'goten', popup: 'Готэн-яки - название керамики, производимой относительно молодой гончарной мастерской, основанной в 1984 году Хидэюки Судзуки. Мастерская расположена в Готене, городе Мураяма, префектура Ямагата, где протекает река Могами, одна из крупнейших рек Японии, часто упоминаемая в исторической поэзии', image: 'goten.webp' },
	{ geocode: [39.45142, 141.07370], tooltip: 'Дай', kanji: '台焼', romaji: 'dai', popup: 'Дайяки - это вид керамики, обжигаемой в городе Ханамаки, префектура Иватэ. Характерной чертой дайяки является бледно-зеленый цвет, называемый "сахарная селадоновая глазурь", или "намакою" (海鼠釉).', image: 'dai.webp' },
	{ geocode: [38.42272, 140.82042], tooltip: 'Дайгамори', kanji: '台ヶ森焼', romaji: 'daigamori', popup: 'Дайгамори - это вид керамики, производимой в префектуре Мияги. Местная глина содержит различные минералы, такие как лигнит, железо и медь, которые, как считается, придают керамике её сложные цвета', image: 'daigamori.webp' },
	{ geocode: [37.48931, 139.92719], tooltip: 'Айдзу Кэйдзан', kanji: '会津慶山焼', romaji: 'aizu keizan', popup: '', image: 'aizu-keizan.webp' },
	{ geocode: [39.40237, 141.02915], tooltip: 'Кадзитё', kanji: '', romaji: 'kajicho', popup: 'Керамика Кадзитё изготавливается на гончсарном круге из глины, добываемой в городе Ханамаки, с добавлением песка из верхнего течения реки Тоёсава. Чайные чашки, сосуды для питья, кувшины и вазы в стиле Кадзитё просты по дизайну и предназначены в основном для повседневного использования. Они отличаются характерными зелеными и молочно-белыми цветами.', image: 'kajicho.webp' },
	{ geocode: [38.60474, 140.74043], tooltip: 'Киригомэ', kanji: '切込焼', romaji: 'kirigome', popup: 'Киригомэ - керамика префектуры Мияги. Киригомэ использует техники, заимствованные из керамики Имари, но её точное происхождение остаётся неизвестным. Самый старый документально подтвержденный датированный предмет, "чайная чашка с сине-белым рисунком граната", был изготовлен в 1835 году.', image: 'kirigome.webp' },
	{ geocode: [43.79144, 142.31217], tooltip: 'Кита Арасияма', kanji: '北の嵐山 北嵐山', romaji: 'kita arashiyama', popup: '', image: 'kita-arashiyama.webp' },
	{ geocode: [43.19535, 141.77832], tooltip: 'Кобуси', kanji: 'こぶ志焼', romaji: 'kobushi', popup: '', image: 'kobushi.webp' },
	{ geocode: [40.17853, 141.75617], tooltip: 'Кокудзи', kanji: '小久慈焼', romaji: 'kokuji', popup: 'Кокудзи-яки - традиционное ремесло, зародившееся в городе Кудзи префектуры Иватэ. С более чем 200-летней историей, оно высоко ценится за  деревенский шарм, составляющими которого являются местная глина и уникальная глазурь из железного песка и пепла рисовой шелухи, которая создает тонкие белые и коричневые оттенки.', image: 'kokuji.webp' },
	{ geocode: [39.46541, 140.37096], tooltip: 'Нараока', kanji: '楢岡焼', romaji: 'naraoka', popup: '', image: 'naraoka.webp' },
	{ geocode: [37.58675, 140.43151], tooltip: 'Нихонмацу Банко', kanji: '二本松萬古焼', romaji: 'nihonmatsu banko', popup: '', image: 'nihonmatsu-banko.webp' },
	{ geocode: [43.18901, 140.99623], tooltip: 'Отару', kanji: '小樽焼', romaji: 'otaru', popup: '', image: 'otaru.webp' },
	{ geocode: [43.05970, 141.35381], tooltip: 'Саппоро', kanji: '札幌焼', romaji: 'sapporo', popup: '', image: 'sapporo.webp' },
	{ geocode: [39.58798, 140.61699], tooltip: 'Сираива', kanji: '白岩焼', romaji: 'shiraiwa', popup: '', image: 'shiraiwa.webp' },
	{ geocode: [37.80103, 140.92096], tooltip: 'Сомакома', kanji: '相馬駒焼', romaji: 'somakoma', popup: '', image: 'somakoma.webp' },
	{ geocode: [37.51683, 139.90717], tooltip: 'Тадзима Банко', kanji: '田島萬古焼', romaji: 'tajima banko', popup: '', image: 'tajima-banko.webp' },
	{ geocode: [36.57008, 136.66437], tooltip: 'Охи', kanji: '大樋焼', romaji: 'ohi', popup: '<a target="_blank" href="/ceramic-styles/ohi">Читать статью</a>', image: 'ohi.webp' },
	{ geocode: [38.93548, 141.12507], tooltip: 'Фудзисава', kanji: '藤沢焼', romaji: 'fujisawa', popup: 'Фудзисава-яки создается путем выдерживания керамики в печи анагама в течение нескольких дней. Характерный цвет достигается за счет сосновой золы, которая прилипает к изделиям во время обжига и плавится. Именно это придает им особый оттенок. Текстура глины простая, но выразительная форма создаёт сильное и характерное ощущение.', image: 'fujisawa.webp' },
	{ geocode: [34.98461, 135.75612], tooltip: 'Раку', kanji: '楽焼', romaji: 'raku', popup: '<a target="_blank" href="/ceramic-styles/raku">Читать статью</a>', image: 'raku.webp' },
	{ geocode: [40.47911, 141.42032], tooltip: 'Хатинохэ', kanji: '八戸焼', romaji: 'hachinohe', popup: '', image: 'hachinohe.webp' },
	{ geocode: [40.81234, 140.50819], tooltip: 'Цугару', kanji: '津軽焼', romaji: 'tsugaru', popup: '', image: 'tsugaru.webp' },
	{ geocode: [38.26807, 140.87190], tooltip: 'Цуцуми', kanji: '堤焼', romaji: 'tsutsumi', popup: 'Зародившись более 300 лет назад в районе Цуцуми города Сэндай, керамика Цуцуми-яки известна своим простым, повседневным дизайном с текучей глазурью "морской огурец". В период своего расцвета в этом районе располагались десятки гончарных мастерских. Сегодня единственной действующей мастерской остается гончарная мастерская Цуцуми-яки Кэмба.', image: 'tsutsumi.webp' },
	{ geocode: [38.24587, 140.33408], tooltip: 'Хирасимидзу', kanji: '平清水焼', romaji: 'hirashimizu', popup: 'Район Хирасимидзу, известный как "Деревня гончаров", расположен у южных предгорий горы Титосэ в юго-восточной части города Ямагата. Говорят, что Оно Тодзихэй, выходец из провинции Хитати, начал создавать местную керамику в эпоху Бунка.', image: 'hirashimizu.webp' },
	{ geocode: [38.57543, 140.51645], tooltip: 'Ками но Хата', kanji: '上の畑焼', romaji: 'kami no hata', popup: 'В префектуре Ямагата находится старейшая фарфоровая печь. Один из её характерных узоров - "Три вкуса", изображающий персики, гранаты и цитрон в форме руки Будды, который был завезён из Китая через Имари. Керамика Ками но Хата - единственная в Японии, где до сих пор используется этот узор.', image: 'kami-no-hata.webp' },
	{ geocode: [38.05842, 140.04996], tooltip: 'Нарусима', kanji: '成島焼', romaji: 'narushima', popup: 'Местная керамика зародилась в 1781 году, когда лорд Уэсуги Ёдзан, построил печь в Нарусиме, княжество Ёнедзава. Печи продолжали работать до конца эпохи Мэйдзи, но с развитием железных дорог их вытеснила дешевая и качественная керамика Сэто, что в конечном итоге привело к их исчезновению. Художник-керамист Фудзио Вакуи потратил около 10 лет, чтобы воссоздать простую и сдержанную текстуру керамики Нарусима', image: 'narushima.webp' },
	{ geocode: [38.75742, 140.31649], tooltip: 'Синдзё Хигасияма', kanji: '新庄東山焼', romaji: 'shinjo higashiyama', popup: 'Вакуи Яхэй, основатель производства хигасиямской керамики, был гончаром из провинции Этиго. Во время своего обучения, путешествуя по разным местам, он влюбился в местную глину и в 1841 году основал печь, ставшую официальной печью княжества Синдзё Тодзава. ', image: 'shinjo-higashiyama.webp' },
	{ geocode: [36.35198, 138.89835], tooltip: 'Дзисёдзи', kanji: '自性寺焼', romaji: 'jishoji', popup: 'Единственная в префектуре Гунма признанная традиционная гончарная мастерская. Вещи Дзисёдзи изготавливаются из  глины, добываемой в регионе Акима города Аннака. Их характерной чертой является элегантная золотая цветочная глазурь, а для росписи используются оригинальные местные глазури, разработанные в результате исследований. В местной мастерской также производится неглазурованная каменная керамика, которая обжигается в дровяной печи в течение семи дней и ночей.', image: 'jishoji.webp' },
	{ geocode: [36.50260, 138.96661], tooltip: 'Сибутами', kanji: '渋民焼', romaji: 'shibutami', popup: 'Основанная в 1986 году Мотоси Имаи и Токой Фукудой, печь Сибутами использует глину и глазурь, добываемые в городе Сибукава, и производит изделия преимущественно с железной глазурью. Хотя традиционно производство красной керамики считалось чрезвычайно сложной задачей, мастерам Сибутами удалось создать неповторимый красный цвет, который обладает уникальной красотой, не похожей ни на что другое.', image: 'shibutami.webp' },
	{ geocode: [36.73963, 138.98463], tooltip: 'Цукиёно', kanji: '月夜野焼', romaji: 'tsukiyono', popup: 'В январе 1975 года в Цукиёно-мати, Тонэ-гун , префектура Гунма (ныне Минаками-мати), Ютаро Фукуда, представитель второго поколения семьи , во время прогулки обнаружил, что грунт, извлеченный при строительстве Синкансэн Дзёэцу, можно использовать в качестве глины для керамики. Было установлено, что большие залежи этой глины распространены в Цукиёно-мати, а также под рекой Окутонэ был обнаружен высококачественный фарфоровый керамический камень. Печь, в которой начали производить местную керамику была расположена ровно посередине между рекой и путём Синкансэн', image: 'tsukiyono.webp' },
	{ geocode: [35.85160, 139.32023], tooltip: 'Ханно', kanji: '飯能焼', romaji: 'hanno', popup: 'Ханно-яки - это керамика, которая когда-то производилась в городе Ханно, префектура Сайтама. Считается, что период производства приходится примерно на 1832 - 1887 год. Примерно с 1975 года производство изделий из Ханно, которые выпускались до периода Мэйдзи возрождается вещи под этим названием стали продаваться в местных магазинах.', image: 'hanno.webp' },
	{ geocode: [36.78845, 140.16175], tooltip: 'Койсаго', kanji: '小砂焼', romaji: 'koisago', popup: 'Местная керамика производится в Коисаго - районе в городе Накагава, префектура Тотиги, где была обнаружена подходящая глина. Начало производству было положено в конце периода Эдо, когда территория входила в состав княжества Мито, и правитель решил производить керамику в пределах княжества.', image: 'koisago.webp' },
	{ geocode: [36.31384, 139.66144], tooltip: 'Микамо', kanji: '三毳焼', romaji: 'mikamo', popup: 'Черепица для крыш провинциальных храмов и женских монастырей провинции Симоцукэ изготавливалась методом обжига уже примерно со времён Хэйан. Микамо-яки - традиционное ремесло, признанное префектурой. Глину, богатую железом, и придающую изделиям деревенский шарм, добывают у подножия горы Микамо. Местные керамические изделия отличаются простотой и теплотой.', image: 'mikamo.webp' },
	{ geocode: [35.71807, 139.80415], tooltip: 'Имадо', kanji: '今戸焼', romaji: 'imado', popup: 'Керамику Имадо обжигали в Имадо, Хасибе и окрестностях в районе Тайто, Токио. Первое упоминание об "изделиях Имадо" встречается в записях 1763 года. В конце периода Эдо около 50 семей изготавливали вещи Имадо, а в эпоху Тэнпо-Ансэй (1830-1860) Имадо был единственным местом производства манэки-нэко. Спрос на вещи из Имадо снизился из-за урбанизации, а также Великого землетрясения Канто и бомбардировок Токио. В настоящее время Юитиро Сираи, мастер-гончар в шестом поколении, является единственным ремесленником по изготовлению вещей Имадо.', image: 'imado.webp' },
	{ geocode: [35.38227, 136.95973], tooltip: 'Инуяма', kanji: '犬山焼', romaji: 'inuyama', popup: 'Инуяма-яки - общее название для керамики, обжигаемой на территории города Инуяма, префектура Айти. Она известна своей белой керамикой, расписанной красной краской. После Реставрации Мэйдзи местная керамика переставала производится, но Сакудзюро Одзэки, ранее работавший изготовителем черепицы, в ноябре 1883 возродил производство.', image: 'inuyama.webp' },
	{ geocode: [35.18621, 136.89849], tooltip: 'Офукэй', kanji: '御深井焼', romaji: 'ofukei', popup: 'Первоначально, в 1660 году, керамика Офукэй обжигалась в Офукэ-мару в замке Нагоя, но этот термин распространился и закрепился для обозначения местной керамики в целом, имеющей зольное покрытие с добавлением полевого шпата, и украшенной формами или печатными узорами.', image: 'ofukei.webp' },
	{ geocode: [36.13554, 137.24007], tooltip: 'Който', kanji: '小糸焼', romaji: 'koito', popup: 'Които-яки — это керамика из города Такаяма, префектура Гифу. Было два периодна, когда производили местную керамику, и обе эти линии прерывались. Современный стиль Които был возрожден после войны Сабуро Нагакурой. Керамика Които известна уникальным стилем и характеризуется глубокой, приглушенной кобальтово-синей глазурью, называемой "Ао-Ирабо", которая является эволюцией Ирабо. 30 марта 1992 года ремесло было признано традиционным ремеслом префектуры Гифу.', image: 'koito.webp' },
	{ geocode: [35.36285, 137.11405], tooltip: 'Орибэ', kanji: '織部焼', romaji: 'oribe', popup: 'Орибэ-яки — это стиль японской керамики, появившийся в шестнадцатом веке и узнаваемый по свободно нанесенной глазури, а также по асимметричным и эксцентричным формам. Многочисленные места расположения печей, где производился Орибе, разбросаны по всему региону Мино.', image: 'oribe.webp' },
	{ geocode: [24.41587, 124.13439], tooltip: 'Исигаки', kanji: '石垣焼', romaji: 'ishigaki', popup: 'Керамика Исигаки-яки тесно связана с керамикой Ёрон-яки, основанной в 1970 году Кихатиро Канеко. Впервые увидев чайную чашу тэммоку, мастер был очарован желанием когда-нибудь изготовить подобную чашу, и это привело его к созданию керамики на острове Ёрон, в то время самом южном острове Японии. Готовясь к открытию гончарной мастерской, он экспериментировал с материалами и разработал технику сплавления стекла и керамики.', image: 'ishigaki.webp' },
	{ geocode: [35.38348, 137.19164], tooltip: 'Сино', kanji: '志野焼', romaji: 'shino', popup: 'Происхождение керамики Сино восходит к периоду Муромати , когда мастер чайной церемонии Сино Сосин заказал гончарам в Мино ее производство. Для Сино характерен толстый слой глазури, а глазурованная поверхность покрыта сетью естественных трещин, с эффектом апельсиновой корки и множеством мелких пор', image: 'shino.webp' },
	{ geocode: [36.14268, 137.23859], tooltip: 'Сибукуса', kanji: '渋草焼', romaji: 'shibukusa', popup: 'Керамика Сибукуса обжигается в городе Такаяма, префектура Гифу. Её производство началось в 1841 году, когда Тойода Томонао, магистрат провинции Хида, основал в Сибукусе совместную государственно-частную печь ди пригласил гончаров из провинций Хидзэн, Овари и Кага, а также художников. 30 марта 1992 года она была признана традиционным ремеслом префектуры Гифу.', image: 'shibukusa.webp' },
	{ geocode: [36.14377, 137.22494], tooltip: 'Ямада', kanji: '山田焼', romaji: 'yamada', popup: 'Керамика ямада - гончарные изделия, обжигаемые в городе Такаяма, префектура Гифу. Считается, что она зародилась в середине периода Эдо, когда гончар из Сэто открыл здесь печь, и начал производство. Ее простой, но привлекательный дизайн, был лишен излишней вычурности и пользовались популярностью. 30 марта 1992 года это ремесло было признано традиционным ремеслом префектуры Гифу. По состоянию на 2006 год только гончарная мастерская Кобаяси производила керамику в народном стиле.', image: 'yamada.webp' },
	{ geocode: [37.44363, 137.26476], tooltip: 'Судзу', kanji: '珠洲焼', romaji: 'suzu', popup: 'Керамика Судзу - один из представительных образцов керамики средневековой Японии, производившийся в окрестностях города Судзу, префектура Исикава, с конца XII века до конца XV ​​века. Она унаследовала технику изготовления <a href="https://en.wikipedia.org/wiki/Sue_pottery" target="_blank">керамики Суэ</a>, которая обжигалась с периода Кофун до периода Хэйан. Изделия Судзу, внезапно исчезнувшие около 400 лет назад, были возрождены городом Судзу в 1976 году. В 1989 году они были признаны традиционным ремеслом префектуры Исикава.', image: 'suzu.webp' },
	{ geocode: [36.56233, 138.18309], tooltip: 'Мацусиро', kanji: '松代焼', romaji: 'matsushiro', popup: 'Керамика Мацусиро возникла около 200 лет назад (в середине периода Эдо), во времена Санады Юкитаки, 7-го правителя княжества Мацусиро. В то время керамику в Мацусиро доставляли верхом на лошадях, и многие изделия разбивались по дороге. Княжество распорядилось изготавливать керамику из местных материалов, и так появилась первые вещи Мацусиро. Сегодня керамика Мацусиро — это традиционное ремесло префектуры Нагано, сертифицированное губернатором префектуры. ', image: 'matsushiro.webp' },
];

// { geocode: [0, 0], tooltip: '', kanji: '', romaji: '', popup: '', image: '.webp' },
// { geocode: [0, 0], tooltip: 'Хораку', kanji: '豊楽焼', romaji: 'horaku', popup: '', image: 'horaku.webp' },

// { geocode: [0, 0], tooltip: 'Обаяси', kanji: '尾林焼', romaji: 'obayashi', popup: '', image: 'obayashi.webp' },
// { geocode: [0, 0], tooltip: 'Такато', kanji: '高遠焼', romaji: 'takato', popup: '', image: 'takato.webp' },
// { geocode: [0, 0], tooltip: 'Тэнрюкё', kanji: '天竜峡焼', romaji: 'tenryukyo', popup: '', image: 'tenryukyo.webp' },
// { geocode: [0, 0], tooltip: 'Анти', kanji: '庵地焼', romaji: 'anchi', popup: '', image: 'anchi.webp' },
// { geocode: [0, 0], tooltip: 'Мурамацу', kanji: '村松焼', romaji: 'muramatsu', popup: '', image: 'muramatsu.webp' },
// { geocode: [0, 0], tooltip: 'Морияма', kanji: '森山焼', romaji: 'moriyama', popup: '', image: 'moriyama.webp' },
// { geocode: [0, 0], tooltip: 'Сидзухата', kanji: '賤機焼', romaji: 'shizuhata', popup: '', image: 'shizuhata.webp' },
// { geocode: [0, 0], tooltip: 'Эттю Маруяма', kanji: '越中丸山焼', romaji: 'etchu maruyama', popup: '', image: 'etchu-maruyama.webp' },
// { geocode: [0, 0], tooltip: 'Эттю Сэто', kanji: '越中瀬戸焼', romaji: 'etchu seto', popup: '', image: 'etchu-seto.webp' },
// { geocode: [0, 0], tooltip: 'Косуги', kanji: '小杉焼', romaji: 'kosugi', popup: '', image: 'kosugi.webp' },
// { geocode: [0, 0], tooltip: 'Сансукэ', kanji: '三助焼', romaji: 'sansuke', popup: '', image: 'sansuke.webp' },
// { geocode: [0, 0], tooltip: 'Нокэцу', kanji: '能穴焼', romaji: 'noketsu', popup: '', image: 'noketsu.webp' },
// { geocode: [0, 0], tooltip: 'Авадзи', kanji: '淡路焼', romaji: 'awaji', popup: '', image: 'awaji.webp' },
// { geocode: [0, 0], tooltip: 'Акоунка', kanji: '赤穂雲火焼', romaji: 'akounka', popup: '', image: 'akounka.webp' },
// { geocode: [0, 0], tooltip: 'Минпэй', kanji: '珉平焼', romaji: 'minpei', popup: '', image: 'minpei.webp' },
// { geocode: [0, 0], tooltip: 'Акоги', kanji: '阿漕焼', romaji: 'akogi', popup: '', image: 'akogi.webp' },
// { geocode: [0, 0], tooltip: 'Михама', kanji: '御浜焼', romaji: 'mihama', popup: '', image: 'mihama.webp' },
// { geocode: [0, 0], tooltip: 'Кикко', kanji: '吉向焼', romaji: 'kikko', popup: '', image: 'kikko.webp' },
// { geocode: [0, 0], tooltip: 'Хатта', kanji: '八田焼', romaji: 'hatta', popup: '', image: 'hatta.webp' },
// { geocode: [0, 0], tooltip: 'Конан', kanji: '湖南焼', romaji: 'konan', popup: '', image: 'konan.webp' },
// { geocode: [0, 0], tooltip: 'Кото', kanji: '湖東焼', romaji: 'koto', popup: '', image: 'koto.webp' },
// { geocode: [0, 0], tooltip: 'Дзуиси', kanji: '瑞芝焼', romaji: 'zuishi', popup: '', image: 'zuishi.webp' },
// { geocode: [0, 0], tooltip: 'Химэтани', kanji: '姫谷焼', romaji: 'himetani', popup: '', image: 'himetani.webp' },
// { geocode: [0, 0], tooltip: 'Миядзима', kanji: '宮島焼', romaji: 'miyajima', popup: '', image: 'miyajima.webp' },
// { geocode: [0, 0], tooltip: 'Хасима', kanji: '羽島焼', romaji: 'hashima', popup: '', image: 'hashima.webp' },
// { geocode: [0, 0], tooltip: 'Мусиакэ', kanji: '虫明焼', romaji: 'mushiake', popup: '', image: 'mushiake.webp' },
// { geocode: [0, 0], tooltip: 'Сакадзу', kanji: '酒津焼', romaji: 'sakazu', popup: '', image: 'sakazu.webp' },
// { geocode: [0, 0], tooltip: 'Бансёдзан', kanji: '萬祥山焼', romaji: 'banshozan', popup: '', image: 'banshozan.webp' },
// { geocode: [0, 0], tooltip: 'Фудзина', kanji: '布志名焼', romaji: 'fujina', popup: '', image: 'fujina.webp' },
// { geocode: [0, 0], tooltip: 'Хатиман', kanji: '八幡焼', romaji: 'hachiman', popup: '', image: 'hachiman.webp' },
// { geocode: [0, 0], tooltip: 'Мидзиро', kanji: '御代焼', romaji: 'mijiro', popup: '', image: 'mijiro.webp' },
// { geocode: [0, 0], tooltip: 'Мори', kanji: '母里焼', romaji: 'mori', popup: '', image: 'mori.webp' },
// { geocode: [0, 0], tooltip: 'Содэси', kanji: '袖師焼', romaji: 'sodeshi', popup: '', image: 'sodeshi.webp' },
// { geocode: [0, 0], tooltip: 'Сюссай', kanji: '出西焼', romaji: 'shussai', popup: '', image: 'shussai.webp' },
// { geocode: [0, 0], tooltip: 'Юноцу', kanji: '温泉津焼', romaji: 'yunotsu', popup: '', image: 'yunotsu.webp' },
// { geocode: [0, 0], tooltip: 'Инкюдзан', kanji: '因久山焼', romaji: 'inkyuzan', popup: '', image: 'inkyuzan.webp' },
// { geocode: [0, 0], tooltip: 'Хоссёдзи', kanji: '法勝寺焼', romaji: 'hosshoji', popup: '', image: 'hosshoji.webp' },
// { geocode: [0, 0], tooltip: 'Кадзува', kanji: '上神焼', romaji: 'kazuwa', popup: '', image: 'kazuwa.webp' },
// { geocode: [0, 0], tooltip: 'Урадомэ', kanji: '浦富焼', romaji: 'uradome', popup: '', image: 'uradome.webp' },
// { geocode: [0, 0], tooltip: 'Усино', kanji: '牛ノ戸焼', romaji: 'ushino', popup: '', image: 'ushino.webp' },
// { geocode: [0, 0], tooltip: 'Сэйри', kanji: '星里焼', romaji: 'seiri', popup: '', image: 'seiri.webp' },
// { geocode: [0, 0], tooltip: 'Суэда', kanji: '末田焼', romaji: 'sueda', popup: '', image: 'sueda.webp' },
// { geocode: [0, 0], tooltip: 'Ракудзан', kanji: '楽山焼', romaji: 'rakuzan', popup: '', image: 'rakuzan.webp' },
// { geocode: [0, 0], tooltip: 'Суйгэцу', kanji: '水月焼', romaji: 'suigetsu', popup: '', image: 'suigetsu.webp' },
// { geocode: [0, 0], tooltip: 'Камикагэ', kanji: '神懸焼', romaji: 'kamikage', popup: '', image: 'kamikage.webp' },
// { geocode: [0, 0], tooltip: 'Окамото', kanji: '岡本焼', romaji: 'okamoto', popup: '', image: 'okamoto.webp' },
// { geocode: [0, 0], tooltip: 'Рихэй', kanji: '理平焼', romaji: 'rihei', popup: '', image: 'rihei.webp' },
// { geocode: [0, 0], tooltip: 'Носаяма', kanji: '能茶山焼', romaji: 'nosayama', popup: '', image: 'nosayama.webp' },
// { geocode: [0, 0], tooltip: 'Одо', kanji: '尾戸焼', romaji: 'odo', popup: '', image: 'odo.webp' },
// { geocode: [0, 0], tooltip: 'Урахарано', kanji: '内原野焼', romaji: 'uraharano', popup: '', image: 'uraharano.webp' },
// { geocode: [0, 0], tooltip: 'Футагава', kanji: '二川焼', romaji: 'futagawa', popup: '', image: 'futagawa.webp' },
// { geocode: [0, 0], tooltip: 'Камати', kanji: '蒲池焼', romaji: 'kamachi', popup: '', image: 'kamachi.webp' },
// { geocode: [0, 0], tooltip: 'Итиносэ', kanji: '一の瀬焼', romaji: 'ichinose', popup: '', image: 'ichinose.webp' },
// { geocode: [0, 0], tooltip: 'Рюмондзи', kanji: '龍門司焼', romaji: 'ryumonji', popup: '', image: 'ryumonji.webp' },
// { geocode: [0, 0], tooltip: 'Танэгасима', kanji: '種子島焼', romaji: 'tanegashima', popup: '', image: 'tanegashima.webp' },
// { geocode: [0, 0], tooltip: 'Кода', kanji: '高田焼', romaji: 'koda', popup: '', image: 'koda.webp' },
// { geocode: [0, 0], tooltip: 'Комацубара', kanji: '小松原焼', romaji: 'komatsubara', popup: '', image: 'komatsubara.webp' },
// { geocode: [0, 0], tooltip: 'Тодзё', kanji: '都城焼', romaji: 'tojo', popup: '', image: 'tojo.webp' },
// { geocode: [0, 0], tooltip: 'Нагаё', kanji: '長与焼', romaji: 'nagayo', popup: '', image: 'nagayo.webp' },
// { geocode: [0, 0], tooltip: 'Уцуцугава', kanji: '現川焼', romaji: 'utsutsugawa', popup: '', image: 'utsutsugawa.webp' },
// { geocode: [0, 0], tooltip: 'Хидзэн Ёсида', kanji: '肥前吉田焼', romaji: 'hizen yoshida', popup: '', image: 'hizen yoshida.webp' },
// { geocode: [0, 0], tooltip: 'Хидзэн Одзаки', kanji: '肥前尾崎焼', romaji: 'hizen ozaki', popup: '', image: 'hizen ozaki.webp' },
// { geocode: [0, 0], tooltip: 'Сираиси', kanji: '白石焼', romaji: 'shiraishi', popup: '', image: 'shiraishi.webp' },
// { geocode: [0, 0], tooltip: 'Рюкю', kanji: '琉球焼', romaji: 'ryukyu', popup: '', image: 'ryukyu.webp' },
