name: Renovate

on:
  schedule:
    # Saturday 00:00 (UTC+5) = Friday 19:00 UTC
    - cron: '0 19 * * 5'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.18
        with:
          configurationFile: renovate.json
          token: '${{ secrets.RENOVATE_TOKEN }}'
